
trigger:
- development
- master

variables:
  extensionVisibility: 'private'

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: PowerShell@2
  displayName: 'Configure version and extension visibility)'
  inputs:
    targetType: 'inline'
    script: |
      $fileContents = Get-Content .\versioninfo.json -Raw
      $versionInfo = ConvertFrom-Json $fileContents
      $vsixVersion = $versionInfo.version + ".$(Build.BuildId)"
      Write-Host "##vso[task.setvariable variable=vsixVersion]$vsixVersion"
      if ($(Build.SourceBranchName) -eq "master") {
        Write-Host "##vso[task.setvariable variable=extensionVisibility]public"
      } else {
        Write-Host "##vso[task.setvariable variable=extensionVisibility]private"
      }

- task: TfxInstaller@2
  inputs:
    version: 'v0.7.x'

- task: PackageAzureDevOpsExtension@2
  inputs:
    rootFolder: 'src'
    outputPath: '$(Pipeline.Workspace)/output/'
    extensionVersion: '$(vsixVersion)'
    updateTasksVersion: true
    extensionVisibility: '$(extensionVisibility)'

- task: PublishAzureDevOpsExtension@2
  inputs:
    connectTo: 'VsTeam'
    connectedServiceName: 'VS Marketplace'
    fileType: 'vsix'
    vsixFile: '$(Pipeline.Workspace)/output/RasmusWatjen.EventGridSubscriptionExtension-$(vsixVersion).vsix'
    updateTasksVersion: false
