# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- development

pool:
  vmImage: 'ubuntu-latest'

variables:
  vsixVersion: '$(MajorVersion).$(MinorVersion).$(Build.BuildId)'

steps:
- task: TfxInstaller@2
  inputs:
    version: 'v0.7.x'


- task: PackageAzureDevOpsExtension@2
  inputs:
    rootFolder: 'src'
    outputPath: '$(Pipeline.Workspace)/output/'
    extensionVersion: '$(vsixVersion)'
    updateTasksVersion: true
    extensionVisibility: 'private'


- task: PublishAzureDevOpsExtension@2
  inputs:
    connectTo: 'VsTeam'
    connectedServiceName: 'VS Marketplace'
    fileType: 'vsix'
    vsixFile: '$(Pipeline.Workspace)/output/RasmusWatjen.EventGridSubscriptionExtension-$(vsixVersion).vsix'
    updateTasksVersion: false
