# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- development

pool:
  vmImage: 'ubuntu-latest'

variables:
  vsixVersion: '$(MajorVersion).$(MinorVersion).$(Build.BuildId)'

stages:
- stage: Build and Publish
  jobs:
  - job: TestOnWindows
    steps:

    - task: TfxInstaller@2
      inputs:
        version: 'v0.7.x'

    - task: PackageAzureDevOpsExtension@2
      inputs:
        rootFolder: 'src'
        outputPath: '$(Pipeline.Workspace)/output/'
        extensionVersion: '$(vsixVersion)'
        updateTasksVersion: true
        extensionVisibility: 'private'


    - task: PublishAzureDevOpsExtension@2
      inputs:
        connectTo: 'VsTeam'
        connectedServiceName: 'VS Marketplace'
        fileType: 'vsix'
        vsixFile: '$(Pipeline.Workspace)/output/RasmusWatjen.EventGridSubscriptionExtension-$(vsixVersion).vsix'
        updateTasksVersion: false

- stage: Test deployment
  jobs:
  - job: Run extension task
    steps:
    - task: RasmusWatjen.EventGridSubscriptionExtension.EventGridSubscriptionExtension.EventGridSubscriptionExtension@0
      displayName: 'Create event subscription in dev-consent-revocation-eu-n-wdx-topic'
      inputs:
        azureSubscription: 'Consent Service Dev'
        ResourceGroupName: 'ConsentService-Dev'
        eventGridTopicName: 'dev-consent-revocation-eu-n-wdx-topic'
        eventSubscriptionName: raswtest
        endpointUrl: 'https://webhook.site/fbb91e60-3e93-4d0b-adf5-187e2ccd505c'
        deadLetterEvents: true
        deadLetterStorageAccountName: devconsentsvceunwdxstg
        deadLetterBlobContainerName: 'eventgrid-deadletters'
        includedEventType: ConsentService.ConsentRevoked

