# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- development

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g tfx-cli 
    cd src
    tfx extension create
  displayName: 'npm install and build'

- task: PackageAzureDevOpsExtension@2
  inputs:
    rootFolder: 'src'
    outputPath: 'output/EventGridSubscriptionExtension.vsix'
    extensionVersion: '$(MajorVersion).$(MinorVersion).$(Build.BuildNumber)'
    updateTasksVersion: true
    extensionVisibility: 'private'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/output/EventGridSubscriptionExtension.vsix'
    artifact: 'EventGridSubscriptionExtension.vsix'